---
abe_nana:
  name:
    last: 安部
    last_kana: あべ
    first: 菜々
    first_kana: なな
  type: cute
  age: 永遠の17歳
  birthday:
    month: 5
    day: 5
  sign: 牡牛座
  blood: a
  height: 146.0
  weight: 40.0
  bust: 84.0
  waist: 57.0
  hip: 84.0
  handed: right
  from: ウサミン星
  favorite:
    - ウサミン星との交信
  cv: 三宅麻理恵
