---
abe_nana:
  name:
    first: 安部
    first_kana: あべ
    last: 菜々
    last_kana: なな
  type: cute
  age: 永遠の17歳
  birthday: 5/5
  sign: 牡牛座
  blood: a
  height: 146.0
  weight: 40.0
  bust: 84
  waist: 57
  hip: 84
  handed: right
  from: ウサミン星
  favorite:
    - ウサミン星との交信
  cv: 三宅麻理恵