---
aiba_yumi:
  name:
    last: 相葉
    last_kana: あいば
    first: 夕美
    first_kana: ゆみ
  type: passion
  age: 18
  birthday:
    month: 4
    day: 15
  sign: 牡羊座
  blood: O
  height: 158.0
  weight: 42.0
  bust: 81.0
  waist: 57.0
  hip: 80.0
  handed: right
  from: 神奈川県
  favorite:
    - ガーデニング
  cv: 木村珠莉
