---
aihara_yukino:
  name:
    last: 相原
    last_kana: あいはら
    first: 雪乃
    first_kana: ゆきの
  type: cute
  age: 22
  birthday:
    month: 2
    day: 14
  sign: 水瓶座
  blood: A
  height: 160.0
  weight: 51.0
  bust: 92.0
  waist: 58.0
  hip: 90.0
  handed: left
  from: 秋田県
  favorite:
    - 紅茶
  cv: ~
