---
akagi_miria:
  name:
    last: 赤城
    last_kana: あかぎ
    first: みりあ
    first_kana: みりあ
  type: passion
  age: 11
  birthday:
    month: 4
    day: 14
  sign: 牡羊座
  blood: AB
  height: 140.0
  weight: 36.0
  bust: 75.0
  waist: 55.0
  hip: 78.0
  handed: left
  from: 東京都
  favorite:
    - おしゃべり
  cv: 黒沢ともよ
