---
akanishi_erika:
  name:
    last: 赤西
    last_kana: あかにし
    first: 瑛梨華
    first_kana: えりか
  type: cute
  age: 16
  birthday: 7/7
  sign: 蟹座
  blood: O
  height: 154.0
  weight: 55.0
  bust: 92
  waist: 59
  hip: 88
  handed: both
  from: 岡山県
  favorite:
    - 漫才鑑賞
  cv: ~
