---
akanishi_erika:
  age: 16
  birthday: 7/7
  blood: O
  bust: 92
  cv: ~
  favorite:
    - 漫才鑑賞
  from: 岡山県
  handed: both
  height: 154.0
  hip: 88
  name:
    first: 赤西
    first_kana: あかにし
    last: 瑛梨華
    last_kana: えりか
  sign: 蟹座
  type: cute
  waist: 59
  weight: 55.0
