---
anastasia:
  name:
    last: ~
    last_kana: ~
    first: アナスタシア
    first_kana: あなすたしあ
  type: cool
  age: 15
  birthday:
    month: 9
    day: 19
  sign: 乙女座
  blood: O
  height: 165.0
  weight: 43.0
  bust: 80.0
  waist: 54.0
  hip: 80.0
  handed: both
  from: 北海道
  favorite:
    - ホームパーティー
    - 天体観測
  cv: 上坂すみれ
