---
anzai_miyako:
  name:
    last: 安斎
    last_kana: あんざい
    first: 都
    first_kana: みやこ
  type: cute
  age: 16
  birthday: 1/6
  sign: 山羊座
  blood: B
  height: 156.0
  weight: 41.0
  bust: 78
  waist: 55
  hip: 77
  handed: right
  from: 福井県
  favorite:
    - 探偵ドラマ
    - 推理小説を読むこと
  cv: ~
