---
araki_hina:
  name:
    last: 荒木
    last_kana: あらき
    first: 比奈
    first_kana: ひな
  type: cool
  age: 20
  birthday:
    month: 4
    day: 9
  sign: 牡羊座
  blood: A
  height: 157.0
  weight: 43.0
  bust: 83.0
  waist: 57.0
  hip: 82.0
  handed: right
  from: 神奈川県
  favorite:
    - 漫画描く
  cv: 田辺留依
