---
ariura_kanna:
  name:
    last: 有浦
    last_kana: ありうら
    first: 柑奈
    first_kana: かんな
  type: cute
  age: 19
  birthday: 3/6
  sign: 魚座
  blood: O
  height: 155.0
  weight: 44.0
  bust: 78
  waist: 57
  hip: 80
  handed: right
  from: 長崎県
  favorite:
    - ラブ&ピース
  cv: ~
