---
asano_fuka:
  name:
    last: 浅野
    last_kana: あさの
    first: 風香
    first_kana: ふうか
  type: cute
  age: 16
  birthday:
    month: 2
    day: 11
  sign: 水瓶座
  blood: A
  height: 160.0
  weight: 48.0
  bust: 88.0
  waist: 59.0
  hip: 84.0
  handed: right
  from: 滋賀県
  favorite:
    - 小説を書くこと
  cv: ~
