---
asari_nanami:
  name:
    last: 浅利
    last_kana: あさり
    first: 七海
    first_kana: ななみ
  type: cool
  age: 14
  birthday:
    month: 10
    day: 9
  sign: 天秤座
  blood: A
  height: 151.0
  weight: 41.0
  bust: 78.0
  waist: 55.0
  hip: 77.0
  handed: right
  from: 青森県
  favorite:
    - 釣り
    - 絵日記
  cv: 井上ほの花
