---
cathy_graham:
  name:
    last: グラハム
    last_kana: ぐらはむ
    first: キャシー
    first_kana: きゃしー
  type: passion
  age: 15
  birthday:
    month: 9
    day: 19
  sign: 乙女座
  blood: O
  height: 168.0
  weight: 49.0
  bust: 83.0
  waist: 56.0
  hip: 85.0
  handed: left
  from: ニューヨーク
  favorite:
    - インラインスケート
    - ダンス
  cv: ~
