---
clarice:
  name:
    last: ~
    last_kana: ~
    first: クラリス
    first_kana: くらりす
  type: cute
  age: 20
  birthday:
    month: 8
    day: 26
  sign: 乙女座
  blood: AB
  height: 166.0
  weight: 45.0
  bust: 80.0
  waist: 55.0
  hip: 82.0
  handed: right
  from: 兵庫県
  favorite:
    - ボランティア
  cv: ~
