---
domyoji_karin:
  name:
    last: 道明寺
    last_kana: どうみょうじ
    first: 歌鈴
    first_kana: かりん
  type: cute
  age: 17
  birthday:
    month:  1
    day: 1
  sign: 山羊座
  blood: A
  height: 155.0
  weight: 43.0
  bust: 80.0
  waist: 55.0
  hip: 83.0
  handed: right
  from: 奈良県
  favorite:
    - 境内のお掃除
  cv: 新田ひより
