---
egami_tsubaki:
  name:
    last: 江上
    last_kana: えがみ
    first: 椿
    first_kana: つばき
  type: cute
  age: 19
  birthday:
    name: 2
    day: 6
  sign: 水瓶座
  blood: A
  height: 161.0
  weight: 46.0
  bust: 80.0
  waist: 57.0
  hip: 80.0
  handed: right
  from: 新潟県
  favorite:
    - 写真を撮ること
  cv: ~
