---
etou_misaki:
  name:
    last: 衛藤
    last_kana: えとう
    first: 美紗希
    first_kana: みさき
  type: passion
  age: 22
  birthday:
    month: 3
    day: 18
  sign: 魚座
  blood: O
  height: 160.0
  weight: 45.0
  bust: 84.0
  waist: 56.0
  hip: 80.0
  handed: left
  from: 大分県
  favorite:
    - 携帯小説
    - 女子力アップ
  cv: ~
