---
eve_santaclaus:
  name:
    last: サンタクロース
    last_kana: さんたくろーす
    first: イブ
    first_kana: いぶ
  type: passion
  age: 19
  birthday: 12/24
  sign: 山羊座
  blood: B
  height: 165.0
  weight: 44.0
  bust: 81
  waist: 56
  hip: 80
  handed: right
  from: グリーンランド
  favorite:
    - 煙突探し
  cv: ~
