---
fujimoto_rina:
  name:
    last: 藤本
    last_kana: ふじもと
    first: 里奈
    first_kana: りな
  type: cute
  age: 18
  birthday:
    month: 10
    day: 14
  sign: 天秤座
  blood: A
  height: 154.0
  weight: 41.0
  bust: 77.0
  waist: 55.0
  hip: 80.0
  handed: right
  from: 神奈川県(湘南市)
  favorite:
    - 単車乗り
    - コンビニで立ち読み
  cv: 金子真由美
