---
fujii_tomo:
  name:
    last: 藤居
    last_kana: ふじい
    first: 朋
    first_kana: とも
  type: cool
  age: 19
  birthday:
    month: 7
    day: 1
  sign: 蟹座
  blood: O
  height: 163.0
  weight: 45.0
  bust: 78.0
  waist: 57.0
  hip: 83.0
  handed: right
  from: 滋賀県
  favorite:
    - 占い
  cv: ~
