---
furusawa_yoriko:
  name:
    last: 古澤
    last_kana: ふるさわ
    first: 頼子
    first_kana: よりこ
  type: cool
  age: 17
  birthday:
    month: 5
    day: 18
  sign: 牡牛座
  blood: A
  height: 166.0
  weight: 45.0
  bust: 81.0
  waist: 59.0
  hip: 83.0
  handed: left
  from: 茨城県
  favorite:
    - 美術展・博物館観覧
  cv: ~
