---
futaba_anzu:
  name:
    last: 双葉
    last_kana: ふたば
    first: 杏
    first_kana: あんず
  type: cute
  age: 17
  birthday:
    month: 9
    day: 2
  sign: 花も恥らう乙女座
  blood: B
  height: 139.0
  weight: 30.0
  bust: '?'
  waist: '?'
  hip: '?'
  handed: right
  from: 北海道
  favorite:
    - なし
  cv: 五十嵐裕美
