---
hamaguchi_ayame:
  name:
    last: 浜口
    last_kana: はまぐち
    first: あやめ
    first_kana: あやめ
  type: passion
  age: 15
  birthday:
    month: 1
    day: 13
  sign: 山羊座
  blood: A
  height: 154.0
  weight: 42.0
  bust: 78.0
  waist: 55.0
  hip: 80.0
  handed: left
  from: 三重県
  favorite:
    - 時代劇鑑賞
    - 忍者グッズ収集
    - 撮影所巡り
  cv: 田澤茉純
