---
harada_miyo:
  name:
    last: 原田
    last_kana: はらだ
    first: 美世
    first_kana: みよ
  type: cute
  age: 20
  birthday: 11/14
  sign: 蠍座
  blood: O
  height: 163.0
  weight: 46.0
  bust: 86
  waist: 59
  hip: 85
  handed: right
  from: 石川県
  favorite:
    - クルマ・バイクいじり
  cv: ~
