---
harada_miyo:
  name:
    last: 原田
    last_kana: はらだ
    first: 美世
    first_kana: みよ
  type: cute
  age: 20
  birthday:
    month: 11
    day: 14
  sign: 蠍座
  blood: O
  height: 163.0
  weight: 46.0
  bust: 86.0
  waist: 59.0
  hip: 85.0
  handed: right
  from: 石川県
  favorite:
    - クルマ・バイクいじり
  cv: ~
