---
hattori_toko:
  name:
    last: 服部
    last_kana: はっとり
    first: 瞳子
    first_kana: とうこ
  type: cool
  age: 25
  birthday:
    name: 10
    day: 11
  sign: 天秤座
  blood: O
  height: 169.0
  weight: 48.0
  bust: 78.0
  waist: 57.0
  hip: 80.0
  handed: left
  from: 大分県
  favorite:
    - 熱帯魚鑑賞
    - 温泉めぐり
  cv: ~
