---
hayasaka_mirei:
  name:
    last: 早坂
    last_kana: はやさか
    first: 美玲
    first_kana: みれい
  type: cute
  age: 14
  birthday:
    month: 5
    day: 9
  sign: 乙女座
  blood: B
  height: 147.0
  weight: 39.0
  bust: 75.0
  waist: 54.0
  hip: 77.0
  handed: right
  from: 宮城県
  favorite:
    - ぬいぐるみ集め
  cv: 朝井彩加
