---
hiiragi_shino:
  name:
    last: 柊
    last_kana: ひいらぎ
    first: 志乃
    first_kana: しの
  type: cool
  age: 31
  birthday:
    month: 12
    day: 25
  sign: 山羊座
  blood: AB
  height: 167.0
  weight: 43.0
  bust: 84.0
  waist: 54.0
  hip: 83.0
  handed: left
  from: 山梨県
  favorite:
    - ワインツーリズム(産地巡り)
  cv: ~
