---
himekawa_yuki:
  name:
    last: 姫川
    last_kana: ひめかわ
    first: 友紀
    first_kana: ゆき
  type: passion
  age: 20
  birthday:
    month: 9
    day: 14
  sign: 乙女座
  blood: A
  height: 161.0
  weight: 44.0
  bust: 80.0
  waist: 57.0
  hip: 80.0
  handed: right
  from: 宮崎県
  favorite:
    - 野球観戦
  cv: 杜野まこ
