---
hino_akane:
  name:
    last: 日野
    last_kana: ひの
    first: 茜
    first_kana: あかね
  type: passion
  age: 17
  birthday: 8/4
  sign: 獅子座
  blood: AB
  height: 148.0
  weight: 40.0
  bust: 80
  waist: 60
  hip: 82
  handed: right
  from: 栃木県
  favorite:
    - ラグビー観戦
  cv: 赤﨑千夏
