---
hisakawa_hayate:
  name:
    last: 久川
    last_kana: ひさかわ
    first: 颯
    first_kana: はやて
  type: cool
  age: 14
  birthday:
    month: 6
    day: 16
  sign: 双子座
  blood: B
  height: 151.0
  weight: 42.0
  bust: 82.0
  waist: 56.0
  hip: 82.0
  handed: right
  from: 徳島県
  favorite:
    - ファッション
    - 流行の店巡り
  cv: 長江里加
