---
hojo_karen:
  name:
    last: 北条
    last_kana: ほうじょう
    first: 加蓮
    first_kana: かれん
  type: cool
  age: 16
  birthday:
    month: 9
    day: 5
  sign: 乙女座
  blood: B
  height: 155.0
  weight: 42.0
  bust: 83.0
  waist: 55.0
  hip: 81.0
  handed: right
  from: 東京都
  favorite:
    - ネイル
  cv: 渕上舞
