---
honda_mio:
  name:
    last: 本田
    last_kana: ほんだ
    first: 未央
    first_kana: みお
  type: passion
  age: 15
  birthday:
    month: 12
    day: 1
  sign: 射手座
  blood: B
  height: 161.0
  weight: 46.0
  bust: 84.0
  waist: 58.0
  hip: 87.0
  handed: right
  from: 千葉県
  favorite:
    - ショッピング
  cv: 原紗友里
