---
hyodo_rena:
  name:
    last: 兵藤
    last_kana: ひょうどう
    first: レナ
    first_kana: れな
  type: cute
  age: 27
  birthday:
    month: 10
    day: 3
  sign: 天秤座
  blood: O
  height: 167.0
  weight: 48.0
  bust: 92.0
  waist: 56.0
  hip: 88.0
  handed: right
  from: 東京都
  favorite:
    - トランプ
  cv: ~
