---
ichihara_nina:
  name:
    last: 市原
    last_kana: いちはら
    first: 仁奈
    first_kana: にな
  type: passion
  age: 9
  birthday:
    month: 2
    day: 8
  sign: 水瓶座
  blood: B
  height: 128.0
  weight: 29.0
  bust: 61.0
  waist: 57.0
  hip: 67.0
  handed: left
  from: 静岡県
  favorite:
    - 着ぐるみ集め
  cv: 久野美咲
