---
ichinose_shiki:
  name:
    last: 一ノ瀬
    last_kana: いちのせ
    first: 志希
    first_kana: しき
  type: cute
  age: 18
  birthday:
    month: 5
    day: 30
  sign: 双子座
  blood: O
  height: 161.0
  weight: 43.0
  bust: 83.0
  waist: 57.0
  hip: 82.0
  handed: right
  from: 岩手県
  favorite:
    - 観察
    - アヤしい科学実験
    - 失踪
  cv: 藍原ことみ
