---
igarashi_kyoko:
  name:
    last: 五十嵐
    last_kana: いがらし
    first: 響子
    first_kana: きょうこ
  type: cute
  age: 15
  birthday:
    month: 8
    day: 10
  sign: 獅子座
  blood: AB
  height: 154.0
  weight: 43.0
  bust: 81.0
  waist: 58.0
  hip: 80.0
  handed: right
  from: 鳥取県
  favorite:
    - 家事全般
  cv: 種崎敦美
