---
ikebukuro_akiha:
  name:
    last: 池袋
    last_kana: いけぶくろ
    first: 晶葉
    first_kana: あきは
  type: cute
  age: 14
  birthday:
    month: 6
    day: 10
  sign: 双子座
  blood: B
  height: 148.0
  weight: 39.0
  bust: 75.0
  waist: 53.0
  hip: 74.0
  handed: right
  from: 東京都
  favorite:
    - ロボット制作
  cv: ~
