---
imai_kana:
  name:
    last: 今井
    last_kana: いまい
    first: 加奈
    first_kana: かな
  type: cute
  age: 16
  birthday:
    month: 3
    day: 3
  sign: 魚座
  blood: O
  height: 153.0
  weight: 41.0
  bust: 81.0
  waist: 56.0
  hip: 70.0
  handed: right
  from: 高知県
  favorite:
    - 友達とおしゃべり
  cv: ~
