---
jougasaki_mika:
  name:
    last: 城ヶ崎
    last_kana: じょうがさき
    first: 美嘉
    first_kana: みか
  type: passion
  age: 17
  birthday:
    month: 11
    day: 12
  sign: 蠍座
  blood: AB
  height: 162.0
  weight: 43.0
  bust: 80.0
  waist: 56.0
  hip: 82.0
  handed: left
  from: 埼玉県
  favorite:
    - カラオケ
  cv: 佳村はるか
