---
jougasaki_mika:
  name:
    last: 城ヶ崎
    last_kana: じょうがさき
    first: 美嘉
    first_kana: みか
  type: passion
  age: 17
  birthday: 11/12
  sign: 蠍座
  blood: AB
  height: 162.0
  weight: 43.0
  bust: 80
  waist: 56
  hip: 82
  handed: left
  from: 埼玉県
  favorite:
    - カラオケ
  cv: 佳村はるか
