---
kamijo_haruna:
  name:
    last: 上条
    last_kana: かみじょう
    first: 春菜
    first_kana: はるな
  type: cool
  age: 18
  birthday:
    month: 4
    day: 10
  sign: 牡羊座
  blood: O
  height: 156.0
  weight: 42.0
  bust: 79.0
  waist: 56.0
  hip: 80.0
  handed: right
  from: 静岡県
  favorite:
    - 猫と縁側でお昼寝
  cv: 長島光那
