---
kanzaki_ranko:
  name:
    last: 神崎
    last_kana: かんざき
    first: 蘭子
    first_kana: らんこ
  type: cool
  age: 14
  birthday:
    month: 4
    day: 8
  sign: 牡羊座
  blood: A
  height: 156.0
  weight: 41.0
  bust: 81.0
  waist: 57.0
  hip: 80.0
  handed: right
  from: 熊本県
  favorite:
    - 絵を描くこと
  cv: 内田真礼
