---
katagiri_sanae:
  name:
    last: 片桐
    last_kana: かたぎり
    first: 早苗
    first_kana: さなえ
  type: passion
  age: 28
  birthday: 3/7
  sign: 魚座
  blood: O
  height: 152.0
  weight: 47.0
  bust: 92
  waist: 58
  hip: 84
  handed: right
  from: 新潟県
  favorite:
    - マッサージ
    - スーパー銭湯
  cv: 和氣あず未
