---
kiba_manami:
  name:
    last: 木場
    last_kana: きば
    first: 真奈美
    first_kana: まなみ
  type: cool
  age: 25
  birthday:
    month: 8
    day: 8
  sign: 獅子座
  blood: AB
  height: 172.0
  weight: 50.0
  bust: 88.0
  waist: 60.0
  hip: 89.0
  handed: right
  from: 長崎県
  favorite:
    - 筋トレ
    - 料理
  cv: ~
