---
kiba_manami:
  name:
    last: 木場
    last_kana: きば
    first: 真奈美
    first_kana: まなみ
  type: cool
  age: 25
  birthday: 8/8
  sign: 獅子座
  blood: AB
  height: 172.0
  weight: 50.0
  bust: 88
  waist: 60
  hip: 89
  handed: right
  from: 長崎県
  favorite:
    - 筋トレ
    - 料理
  cv: ~
