---
kimura_natsuki:
  name:
    last: 木村
    last_kana: きむら
    first: 夏樹
    first_kana: なつき
  type: passion
  age: 18
  birthday: 8/19
  sign: 獅子座
  blood: AB
  height: 159.0
  weight: 41.0
  bust: 82
  waist: 57
  hip: 83
  handed: left
  from: 茨城県
  favorite:
    - ツーリング
  cv: 安野希世乃
