---
kiryu_tsukasa:
  name:
    last: 桐生
    last_kana: きりゅう
    first: つかさ
    first_kana: つかさ
  type: cool
  age: 18
  birthday:
    month: 2
    day: 24
  sign: 魚座
  blood: A
  height: 164.0
  weight: 45.0
  bust: 83.0
  waist: 55.0
  hip: 82.0
  handed: right
  from: 福井県
  favorite:
    - 異業種交流
    - ホットヨガ
    - ぬか床の世話
  cv: 河瀬茉希
