---
kitami_yuzu:
  name:
    last: 喜多見
    last_kana: きたみ
    first: 柚
    first_kana: ゆず
  type: passion
  age: 15
  birthday:
    month: 12
    day: 2
  sign: 射手座
  blood: B
  height: 156.0
  weight: 43.0
  bust: 82.0
  waist: 57.0
  hip: 82.0
  handed: left
  from: 埼玉県
  favorite:
    - バトミントン
  cv: 武田羅梨沙多胡
