---
kitagawa_mahiro:
  name:
    last: 北川
    last_kana: きたがわ
    first: 真尋
    first_kana: まひろ
  type: passion
  age: 17
  birthday:
    month: 2
    day: 17
  sign: 水瓶座
  blood: O
  height: 158.0
  weight: 43.0
  bust: 75.0
  waist: 57.0
  hip: 79.0
  handed: right
  from: 香川県
  favorite:
    - 走ること
    - 食べること
    - 寝ること
  cv: ~
