---
kita_hinako:
  name:
    last: 喜多
    last_kana: きた
    first: 日菜子
    first_kana: ひなこ
  type: passion
  age: 15
  birthday:
    month: 4
    day: 6
  sign: 牡牛座
  blood: AB
  height: 151.0
  weight: 38.0
  bust: 78.0
  waist: 56.0
  hip: 78.0
  handed: right
  from: 秋田県
  favorite:
    - 妄想
  cv: 深川芹亜
