---
koga_koharu:
  name:
    last: 古賀
    last_kana: こが
    first: 小春
    first_kana: こはる
  type: cute
  age: 12
  birthday:
    month: 4
    day: 1
  sign: 牡羊座
  blood: O
  height: 140.0
  weight: 35.0
  bust: 72.0
  waist: 54.0
  hip: 77.0
  handed: left
  from: 佐賀県
  favorite:
    - イグアナのヒョウくんと遊ぶこと
    - 家のお手伝い
  cv: ~
