---
koga_koharu:
  name:
    last: 古賀
    last_kana: こが
    first: 小春
    first_kana: こはる
  type: cute
  age: 12
  birthday: 4/1
  sign: 牡羊座
  blood: O
  height: 140.0
  weight: 35.0
  bust: 72
  waist: 54
  hip: 77
  handed: left
  from: 佐賀県
  favorite:
    - イグアナのヒョウくんと遊ぶこと
    - 家のお手伝い
  cv: ~
