---
komatsu_ibuki:
  name:
    last: 小松
    last_kana: こまつ
    first: 伊吹
    first_kana: いぶき
  type: passion
  age: 19
  birthday:
    month: 11
    day: 17
  sign: 蠍座
  blood: O
  height: 165.0
  weight: 48.0
  bust: 85.0
  waist: 59.0
  hip: 88.0
  handed: right
  from: 茨城県
  favorite:
    - ストリートダンス
    - スケボー
    - 恋愛映画を見る事
  cv: ~
