---
komuro_chinami:
  name:
    last: 小室
    last_kana: こむろ
    first: 千奈美
    first_kana: ちなみ
  type: cool
  age: 19
  birthday:
    month: 6
    day: 9
  sign: 双子座
  blood: AB
  height: 164.0
  weight: 45.0
  bust: 84.0
  waist: 56.0
  hip: 82.0
  handed: right
  from: 愛知県
  favorite:
    - ダーツ
  cv: ~
