---
koseki_reina:
  name:
    last: 小関
    last_kana: こせき
    first: 麗奈
    first_kana: れいな
  type: passion
  age: 13
  birthday:
    month: 3
    day: 5
  sign: 魚座
  blood: B
  height: 148.0
  weight: 41.0
  bust: 75.0
  waist: 50.0
  hip: 77.0
  handed: right
  from: 山形県
  favorite:
    - いたずら
  cv: 長野佑紀
