---
koshimizu_sachiko:
  name:
    last: 輿水
    last_kana: こしみず
    first: 幸子
    first_kana: さちこ
  type: cute
  age: 14
  birthday: 11/25
  sign: 射手座
  blood: B
  height: 142.0
  weight: 37.0
  bust: 74
  waist: 52
  hip: 75
  handed: left
  from: 山梨県
  favorite:
    - 勉強ノートの清書
  cv: 竹達彩奈
