---
kurihara_nene:
  name:
    last: 栗原
    last_kana: くりはら
    first: ネネ
    first_kana: ねね
  type: cute
  age: 15
  birthday:
    month: 9
    day: 9
  sign: 乙女座
  blood: A
  height: 161.0
  weight: 44.0
  bust: 77.0
  waist: 54.0
  hip: 78.0
  handed: right
  from: 群馬県
  favorite:
    - テレビ鑑賞
    - 健康作り
  cv: ~
