---
kurosaki_chitose:
  name:
    last: 黒埼
    last_kana: くろさき
    first: ちとせ
    first_kana: ちとせ
  type: cute
  age: 17
  birthday:
    month: 11
    day: 10
  sign: 蠍座
  blood: O
  height: 165.0
  weight: 44.0
  bust: 86.0
  waist: 58.0
  hip: 84.0
  handed: right
  from: 東京都
  favorite:
    - 美味しいものを食べること
    - 月光浴
  cv: 佐倉薫
