---
kusakabe_wakaba:
  name:
    last: 日下部
    last_kana: くさかべ
    first: 若葉
    first_kana: わかば
  type: cute
  age: 20
  birthday:
    month: 5
    day: 4
  sign: 牡羊座
  blood: O
  height: 148.0
  weight: 40.0
  bust: 77.0
  waist: 54.0
  hip: 78.0
  handed: right
  from: 群馬県
  favorite:
    - ジグソーパズル
  cv: ~
