---
maekawa_miku:
  name:
    last: 前川
    last_kana: まえかわ
    first: みく
    first_kana: みく
  type: cute
  age: 15
  birthday:
    month: 2
    day: 22
  sign: 魚座
  blood: B
  height: 152.0
  weight: 45.0
  bust: 85.0
  waist: 55.0
  hip: 81.0
  handed: right
  from: 大阪府
  favorite:
    - 猫カフェ巡り
  cv: 高森奈津美
