---
makihara_shiho:
  name:
    last: 槙原
    last_kana: まきはら
    first: 志保
    first_kana: しほ
  type: passion
  age: 19
  birthday:
    month: 4
    day: 27
  sign: 牡牛座
  blood: B
  height: 162.0
  weight: 46.0
  bust: 86.0
  waist: 57.0
  hip: 91.0
  handed: right
  from: 三重県
  favorite:
    - スイーツ巡り
  cv: ~
