---
makihara_shiho:
  name:
    first: 槙原
    first_kana: まきはら
    last: 志保
    last_kana: しほ
  type: passion
  age: 19
  birthday: 4/27
  sign: 牡牛座
  blood: B
  height: 162.0
  weight: 46.0
  bust: 86
  waist: 57
  hip: 91
  handed: right
  from: 三重県
  favorite:
    - スイーツ巡り
  cv: ~
