---
manaka_misato:
  name:
    last: 間中
    last_kana: まなか
    first: 美里
    first_kana: みさと
  type: cute
  age: 20
  birthday:
    month: 11
    day: 6
  sign: 蠍座
  blood: AB
  height: 160.0
  weight: 46.0
  bust: 84.0
  waist: 57.0
  hip: 85.0
  handed: right
  from: 神奈川県
  favorite:
    - 旅行
  cv: ~
