---
manaka_misato:
  name:
    last: 間中
    last_kana: まなか
    first: 美里
    first_kana: みさと
  type: cute
  age: 20
  birthday: 11/6
  sign: 蠍座
  blood: AB
  height: 160.0
  weight: 46.0
  bust: 84
  waist: 57
  hip: 85
  handed: right
  from: 神奈川県
  favorite:
    - 旅行
  cv: ~
