---
mary_cochran:
  name:
    last: コクラン
    last_kana: こくらん
    first: メアリー
    first_kana: めありー
  type: passion
  age: 11
  birthday:
    month: 1
    day: 19
  sign: 山羊座
  blood: B
  height: 152.0
  weight: 41.0
  bust: 71.0
  waist: 59.0
  hip: 73.0
  handed: left
  from: アメリカ(サンフランシスコ)
  favorite:
    - 女磨き
    - グルメツアー
  cv: ~
