---
matoba_risa:
  name:
    last: 的場
    last_kana: まとば
    first: 梨沙
    first_kana: りさ
  type: passion
  age: 12
  birthday:
    month: 11
    day: 19
  sign: 蠍座
  blood: B
  height: 143.0
  weight: 38.0
  bust: 71.0
  waist: 58.0
  hip: 73.0
  handed: right
  from: 山口県
  favorite:
    - ダンス
    - パパとデート
  cv: 集貝はな
