---
matsunaga_ryo:
  name:
    last: 松永
    last_kana: まつなが
    first: 涼
    first_kana: りょう
  type: cool
  age: 18
  birthday:
    month: 10
    day: 1
  sign: 天秤座
  blood: AB
  height: 160.0
  weight: 47.0
  bust: 90.0
  waist: 56.0
  hip: 86.0
  handed: right
  from: 東京都
  favorite:
    - ホラー映画鑑賞
  cv: 千菅春香
