---
mifune_miyu:
  name:
    last: 三船
    last_kana: みふね
    first: 美優
    first_kana: みゆ
  type: cool
  age: 26
  birthday:
    month: 2
    day: 25
  sign: 魚座
  blood: AB
  height: 165.0
  weight: 46.0
  bust: 85.0
  waist: 60.0
  hip: 85.0
  handed: right
  from: 岩手県
  favorite:
    - アロマテラピー
  cv: 原田彩楓
