---
miyamoto_frederica:
  name:
    last: 宮本
    last_kana: みやもと
    first: フレデリカ
    first_kana: ふれでりか
  type: cute
  age: 19
  birthday:
    month: 2
    day: 14
  sign: 水瓶座
  blood: B
  height: 164.0
  weight: 46.0
  bust: 83.0
  waist: 57.0
  hip: 85.0
  handed: left
  from: フランス(パリ)
  favorite:
    - ファッション
  cv: 髙野麻美
