---
miyoshi_sana:
  name:
    last: 三好
    last_kana: みよし
    first: 紗南
    first_kana: さな
  type: passion
  age: 14
  birthday:
    month: 6
    day: 25
  sign: 蟹座
  blood: B
  height: 149.0
  weight: 39.0
  bust: 75.0
  waist: 56.0
  hip: 80.0
  handed: right
  from: 香川県
  favorite:
    - TVゲーム
    - 夜更し
  cv: ~
