---
mizuno_midori:
  name:
    last: 水野
    last_kana: みずの
    first: 翠
    first_kana: みどり
  type: cool
  age: 18
  birthday: 12/5
  sign: 射手座
  blood: AB
  height: 164.0
  weight: 47.0
  bust: 80
  waist: 54
  hip: 81
  handed: right
  from: 愛知県
  favorite:
    - 弓道
  cv: ~
