---
mizuno_midori:
  name:
    first: 水野
    first_kana: みずの
    last: 翠
    last_kana: みどり
  type: cool
  age: 18
  birthday: 12/5
  sign: 射手座
  blood: AB
  height: 164.0
  weight: 47.0
  bust: 80
  waist: 54
  hip: 81
  handed: right
  from: 愛知県
  favorite:
    - 弓道
  cv: ~