---
mizuno_midori:
  name:
    last: 水野
    last_kana: みずの
    first: 翠
    first_kana: みどり
  type: cool
  age: 18
  birthday:
    month: 12
    day: 5
  sign: 射手座
  blood: AB
  height: 164.0
  weight: 47.0
  bust: 80.0
  waist: 54.0
  hip: 81.0
  handed: right
  from: 愛知県
  favorite:
    - 弓道
  cv: ~
