---
mochida_arisa:
  name:
    last: 持田
    last_kana: もちだ
    first: 亜里沙
    first_kana: ありさ
  type: cute
  age: 21
  birthday:
    month: 8
    day: 24
  sign: 乙女座
  blood: AB
  height: 156.0
  weight: 45.0
  bust: 77.0
  waist: 54.0
  hip: 76.0
  handed: right
  from: 長野県
  favorite:
    - 子供と遊ぶこと
  cv: ~
