---
momoi_azuki:
  name:
    last: 桃井
    last_kana: ももい
    first: あずき
    first_kana: あずき
  type: cute
  age: 15
  birthday:
    month: 7
    day: 7
  sign: 蟹座
  blood: A
  height: 145.0
  weight: 40.0
  bust: 80.0
  waist: 55.0
  hip: 78.0
  handed: right
  from: 長野県
  favorite:
    - 金魚すくい
  cv: ~
