---
mukai_takumi:
  name:
    last: 向井
    last_kana: むかい
    first: 拓海
    first_kana: たくみ
  type: passion
  age: 18
  birthday:
    month: 8
    day: 7
  sign: 獅子座
  blood: A
  height: 163.0
  weight: 53.0
  bust: 95.0
  waist: 60.0
  hip: 87.0
  handed: right
  from: 神奈川県
  favorite:
    - バイクいじり
  cv: 原優子
