---
munakata_atsumi:
  name:
    last: 棟方
    last_kana: むなかた
    first: 愛海
    first_kana: あつみ
  type: cute
  age: 14
  birthday:
    month: 8
    day: 1
  sign: 獅子座
  blood: A
  height: 151.0
  weight: 41.0
  bust: 73.0
  waist: 56.0
  hip: 75.0
  handed: both
  from: 青森県
  favorite:
    - 指の運動
  cv: 藤本彩花
