---
muramatsu_sakura:
  name:
    last: 村松
    last_kana: むらまつ
    first: さくら
    first_kana: さくら
  type: cute
  age: 15
  birthday:
    month: 3
    day: 27
  sign: 牡羊座
  blood: O
  height: 145.0
  weight: 38.0
  bust: 75.0
  waist: 55.0
  hip: 77.0
  handed: right
  from: 静岡県
  favorite:
    - ピンクのもの集め
  cv: ~
