---
murakami_tomoe:
  name:
    first: 村上
    first_kana: むらかみ
    last: 巴
    last_kana: ともえ
  type: passion
  age: 13
  birthday: 1/3
  sign: 山羊座
  blood: A
  height: 143.0
  weight: 37.0
  bust: 74
  waist: 53
  hip: 76
  handed: right
  from: 広島県
  favorite:
    - 演歌
    - 将棋
  花井美春: cv
