---
murakami_tomoe:
  name:
    last: 村上
    last_kana: むらかみ
    first: 巴
    first_kana: ともえ
  type: passion
  age: 13
  birthday:
    month: 1
    day: 3
  sign: 山羊座
  blood: A
  height: 143.0
  weight: 37.0
  bust: 74.0
  waist: 53.0
  hip: 76.0
  handed: right
  from: 広島県
  favorite:
    - 演歌
    - 将棋
  花井美春: cv
