---
namba_emi:
  name:
    first: 難波
    first_kana: なんば
    last: 笑美
    last_kana: えみ
  type: passion
  age: 17
  birthday: 5/1
  sign: 牡牛座
  blood: O
  height: 158.0
  weight: 45.0
  bust: 82
  waist: 56
  hip: 80
  handed: right
  from: 大阪府
  favorite:
    - お笑いライブ巡り
    - モノマネ
  cv: 伊達朱里紗
