---
namba_emi:
  name:
    last: 難波
    last_kana: なんば
    first: 笑美
    first_kana: えみ
  type: passion
  age: 17
  birthday:
    month: 5
    day: 1
  sign: 牡牛座
  blood: O
  height: 158.0
  weight: 45.0
  bust: 82.0
  waist: 56.0
  hip: 80.0
  handed: right
  from: 大阪府
  favorite:
    - お笑いライブ巡り
    - モノマネ
  cv: 伊達朱里紗
