---
namiki_meiko:
  name:
    last: 並木
    last_kana: なみき
    first: 芽衣子
    first_kana: めいこ
  type: passion
  age: 22
  birthday:
    month: 10
    day: 14
  sign: 天秤座
  blood: AB
  height: 160.0
  weight: 44.0
  bust: 80.0
  waist: 57.0
  hip: 82.0
  handed: right
  from: 和歌山県
  favorite:
    - 旅行
  cv: ~
