---
nanjo_hikaru:
  name:
    first: 南条
    first_kana: なんじょう
    last: 光
    last_kana: ひかる
  type: passion
  age: 14
  birthday: 9/13
  sign: 乙女座
  blood: B
  height: 140.0
  weight: 41.0
  bust: 79
  waist: 58
  hip: 80
  handed: right
  from: 徳島県
  favorite:
    - 特撮番組鑑賞
    - 特撮ごっこ
  cv: 神谷早矢佳
