---
nanjo_hikaru:
  name:
    last: 南条
    last_kana: なんじょう
    first: 光
    first_kana: ひかる
  type: passion
  age: 14
  birthday:
    month: 9
    day: 13
  sign: 乙女座
  blood: B
  height: 140.0
  weight: 41.0
  bust: 79.0
  waist: 58.0
  hip: 80.0
  handed: right
  from: 徳島県
  favorite:
    - 特撮番組鑑賞
    - 特撮ごっこ
  cv: 神谷早矢佳
