---
narumiya_yume:
  name:
    last: 成宮
    last_kana: なるみや
    first: 由愛
    first_kana: ゆめ
  type: cool
  age: 13
  birthday:
    month: 11
    day: 3
  sign: 蠍座
  blood: AB
  height: 150.0
  weight: 40.0
  bust: 72.0
  waist: 51.0
  hip: 73.0
  handed: both
  from: 滋賀県
  favorite:
    - 写生
    - 水彩画
  cv: ~
