---
natalia:
  name:
    last: ~
    last_kana: ~
    first: ナターリア
    first_kana: なたーりあ
  type: passion
  age: 14
  birthday:
    month: 6
    day: 29
  sign: 蟹座
  blood: A
  height: 155.0
  weight: 43.0
  bust: 84.0
  waist: 55.0
  hip: 86.0
  handed: right
  from: リオ・デ・ジャネイロ
  favorite:
    - ベリーダンス
  cv: 生田輝
