---
ninomiya_asuka:
  name:
    last: 二宮
    last_kana: にのみや
    first: 飛鳥
    first_kana: あすか
  type: cool
  age: 14
  birthday:
    month: 2
    day: 3
  sign: 水瓶座
  blood: B
  height: 154.0
  weight: 43.0
  bust: 75.0
  waist: 55.0
  hip: 78.0
  handed: right
  from: 静岡県
  favorite:
    - ヘアアレンジ
    - ラジオを聴くこと
    - 漫画を描くこと
  cv: 青木志貴
