---
nishikawa_honami:
  name:
    last: 西川
    last_kana: にしかわ
    first: 保奈美
    first_kana: ほなみ
  type: cool
  age: 16
  birthday:
    month: 10
    day: 23
  sign: 天秤座
  blood: A
  height: 155.0
  weight: 55.0
  bust: 88.0
  waist: 60.0
  hip: 86.0
  handed: both
  from: 兵庫県
  favorite:
    - オペラ鑑賞
    - 宝塚鑑賞
  cv: ~
