---
nitta_minami:
  name:
    last: 新田
    last_kana: にった
    first: 美波
    first_kana: みなみ
  type: cool
  age: 19
  birthday:
    month: 7
    day: 27
  sign: 獅子座
  blood: O
  height: 165.0
  weight: 45.0
  bust: 82.0
  waist: 55.0
  hip: 85.0
  handed: right
  from: 広島県
  favorite:
    - ラクロス
    - 資格取得
  cv: 洲崎綾
