---
niwa_hitomi:
  name:
    last: 丹羽
    last_kana: にわ
    first: 仁美
    first_kana: ひとみ
  type: cute
  age: 18
  birthday:
    month: 6
    day: 4
  sign: 双子座
  blood: B
  height: 157.0
  weight: 43.0
  bust: 81.0
  waist: 55.0
  hip: 79.0
  handed: right
  from: 愛知県(名古屋市)
  favorite:
    - 史跡巡り
    - 武将グッズ収集
  cv: ~
