---
ogata_chieri:
  name:
    last: 緒方
    last_kana: おがた
    first: 智絵里
    first_kana: ちえり
  type: cute
  age: 16
  birthday:
    month: 6
    day: 11
  sign: 双子座
  blood: A
  height: 153.0
  weight: 42.0
  bust: 79.0
  waist: 57.0
  hip: 80.0
  handed: right
  from: 三重県
  favorite:
    - 四葉のクローバー集め
  cv: 大空直美
