---
ohara_michiru:
  name:
    last: 大原
    last_kana: おおはら
    first: みちる
    first_kana: みちる
  type: cute
  age: 15
  birthday:
    month: 4
    day: 12
  sign: 牡羊座
  blood: O
  height: 153.0
  weight: 40.0
  bust: 78.0
  waist: 55.0
  hip: 80.0
  handed: right
  from: 福井県
  favorite:
    - 食べること
  cv: ~
