---
ohta_yu:
  name:
    last: 太田
    last_kana: おおた
    first: 優
    first_kana: ゆう
  type: cute
  age: 21
  birthday:
    month: 1
    day: 28
  sign: 水瓶座
  blood: AB
  height: 159.0
  weight: 45.0
  bust: 89
  waist: 57
  hip: 87
  handed: right
  from: 千葉県
  favorite:
    - 犬のトリミング
    - 美容
  cv: ~
