---
oikawa_shizuku:
  name:
    last: 及川
    last_kana: おいかわ
    first: 雫
    first_kana: しずく
  type: passion
  age: 16
  birthday: 6/3
  sign: 双子座
  blood: O
  height: 170.0
  weight: 56.0
  bust: 105
  waist: 64
  hip: 92
  handed: both
  from: 岩手県
  favorite:
    - 乳搾り
    - トラクターの運転
  cv: のぐちゆり
