---
okazaki_yasuha:
  name:
    last: 岡崎
    last_kana: おかざき
    first: 泰葉
    first_kana: やすは
  type: cool
  age: 16
  birthday:
    month: 7
    day: 16
  sign: 蟹座
  blood: A
  height: 153.0
  weight: 43.0
  bust: 70.0
  waist: 55.0
  hip: 80.0
  handed: left
  from: 長崎県
  favorite:
    - ドールハウス作り
  cv: ~
