---
okuyama_saori:
  name:
    last: 奥山
    last_kana: おくやま
    first: 沙織
    first_kana: さおり
  type: cute
  age: 19
  birthday:
    month: 6
    day: 12
  sign: 双子座
  blood: B
  height: 156.0
  weight: 47.0
  bust: 83.0
  waist: 57.0
  hip: 81.0
  handed: right
  from: 秋田県
  favorite:
    - 読書
  cv: ~
