---
ryuzaki_kaoru:
  name:
    last: 龍崎
    last_kana: りゅうざき
    first: 薫
    first_kana: かおる
  type: passion
  age: 9
  birthday:
    month: 7
    day: 20
  sign: 蟹座
  blood: O
  height: 132.0
  weight: 32.0
  bust: 65.0
  waist: 51.0
  hip: 70.0
  handed: right
  from: 愛媛県
  favorite:
    - 料理
  cv: 春瀬なつみ
