---
saejima_kiyomi:
  name:
    last: 冴島
    last_kana: さえじま
    first: 清美
    first_kana: きよみ
  type: passion
  age: 15
  birthday: 9/26
  sign: 天秤座
  blood: A
  height: 153.0
  weight: 43.0
  bust: 76
  waist: 58
  hip: 78
  handed: right
  from: 沖縄県
  favorite:
    - 掃除
    - 整理整頓
    - 腕章作り
  cv: ~
