---
saejima_kiyomi:
  name:
    last: 冴島
    last_kana: さえじま
    first: 清美
    first_kana: きよみ
  type: passion
  age: 15
  birthday:
    month: 9
    day: 26
  sign: 天秤座
  blood: A
  height: 153.0
  weight: 43.0
  bust: 76.0
  waist: 58.0
  hip: 78.0
  handed: right
  from: 沖縄県
  favorite:
    - 掃除
    - 整理整頓
    - 腕章作り
  cv: ~
