---
sagisawa_fumika:
  name:
    last: 鷺沢
    last_kana: さぎさわ
    first: 文香
    first_kana: ふみか
  type: cool
  age: 19
  birthday:
    month: 10
    day: 27
  sign: 蠍座
  blood: AB
  height: 162.0
  weight: 45.0
  bust: 84.0
  waist: 54.0
  hip: 81.0
  handed: right
  from: 長野県
  favorite:
    - 本屋めぐり
    - 栞づくり
  cv: M・A・O
