---
saionji_kotoka:
  name:
    last: 西園寺
    last_kana: さいおんじ
    first: 琴歌
    first_kana: ことは
  type: cute
  age: 17
  birthday:
    month: 1
    day: 23
  sign: 水瓶座
  blood: O
  height: 156.0
  weight: 46.0
  bust: 87.0
  waist: 57.0
  hip: 85.0
  handed: right
  from: 東京都
  favorite:
    - 押し花作り
  cv: ~
