---
saionji_kotoka:
  name:
    last: 西園寺
    last_kana: さいおんじ
    first: 琴歌
    first_kana: ことは
  type: cute
  age: 17
  birthday: 1/23
  sign: 水瓶座
  blood: O
  height: 156.0
  weight: 46.0
  bust: 87
  waist: 57
  hip: 85
  handed: right
  from: 東京都
  favorite:
    - 押し花作り
  cv: ~
