---
saito_yoko:
  name:
    last: 斉藤
    last_kana: さいとう
    first: 洋子
    first_kana: ようこ
  type: passion
  age: 20
  birthday:
    month: 12
    day: 29
  sign: 山羊座
  blood: O
  height: 157.0
  weight: 46.0
  bust: 85.0
  waist: 57.0
  hip: 82.0
  handed: right
  from: 福岡県
  favorite:
    - 半身浴
  cv: ~
