---
sajo_yukimi:
  name:
    last: 佐城
    last_kana: さじょう
    first: 雪美
    first_kana: ゆきみ
  type: cool
  age: 10
  birthday:
    month: 9
    day: 28
  sign: 天秤座
  blood: AB
  height: 137.0
  weight: 30.0
  bust: 63.0
  waist: 47.0
  hip: 65.0
  handed: right
  from: 京都府
  favorite:
    - ペット（黒猫）と会話
  cv: 中澤ミナ
