---
sajo_yukimi:
  name:
    first: 佐城
    first_kana: さじょう
    last: 雪美
    last_kana: ゆきみ
  type: cool
  age: 10
  birthday: 9/28
  sign: 天秤座
  blood: AB
  height: 137.0
  weight: 30.0
  bust: 63
  waist: 47
  hip: 65
  handed: right
  from: 京都府
  favorite:
    - ペット（黒猫）と会話
  cv: 中澤ミナ