---
sakurai_momoka:
  name:
    last: 櫻井
    last_kana: さくらい
    first: 桃華
    first_kana: ももか
  type: cute
  age: 12
  birthday: 4/8
  sign: 牡羊座
  blood: A
  height: 145.0
  weight: 39.0
  bust: 72
  waist: 53
  hip: 75
  handed: right
  from: 兵庫県(神戸市)
  favorite:
    - ティータイム
  cv: 照井春佳
