---
sasaki_chie:
  name:
    last: 佐々木
    last_kana: ささき
    first: 千枝
    first_kana: ちえ
  type: cool
  age: 11
  birthday:
    month: 6
    day: 7
  sign: 双子座
  blood: AB
  height: 139.0
  weight: 33.0
  bust: 73.0
  waist: 49.0
  hip: 73.0
  handed: left
  from: 富山県
  favorite:
    - 裁縫
  cv: 今井麻夏
