---
sato_shin:
  name:
    last: 佐藤
    last_kana: さとう
    first: 心
    first_kana: しん
  type: passion
  age: 26
  birthday:
    month: 7
    day: 22
  sign: 蟹座
  blood: AB
  height: 166.0
  weight: ダイエットちゅう
  bust: ぼんっ
  waist: きゅっ
  hip: ぼんっ♪
  handed: right
  from: 長野県
  favorite:
    - ドレスアップ
    - 衣装作り
  cv: 花守ゆみり
