---
sawada_marina:
  name:
    last: 沢田
    last_kana: さわだ
    first: 麻理菜
    first_kana: まりな
  type: passion
  age: 26
  birthday: 5/6
  sign: 牡牛座
  blood: B
  height: 166.0
  weight: 47.0
  bust: 87
  waist: 57
  hip: 87
  handed: right
  from: 長野県
  favorite:
    - サーフィン
  cv: ~
