---
senzaki_ema:
  name:
    last: 仙崎
    last_kana: せんざき
    first: 恵磨
    first_kana: えま
  type: passion
  age: 21
  birthday:
    month: 6
    day: 27
  sign: 蟹座
  blood: O
  height: 156.0
  weight: 45.0
  bust: 81.0
  waist: 55.0
  hip: 81.0
  handed: left
  from: 大阪府
  favorite:
    - 革小物集め
  cv: ~
