---
shibuya_rin:
  name:
    last: 渋谷
    last_kana: しぶや
    first: 凛
    first_kana: りん
  type: cool
  age: 15
  birthday:
    month: 8
    day: 10
  sign: 獅子座
  blood: B
  height: 165.0
  weight: 44.0
  bust: 80.0
  waist: 56.0
  hip: 81.0
  handed: right
  from: 東京都
  favorite:
    - 犬の散歩
  cv: 福原綾香
