---
shiina_noriko:
  name:
    last: 椎名
    last_kana: しいな
    first: 法子
    first_kana: のりこ
  type: cute
  age: 13
  birthday:
    month: 10
    day: 10
  sign: 天秤座
  blood: O
  height: 147.0
  weight: 38.0
  bust: 76.0
  waist: 55.0
  hip: 79.0
  handed: right
  from: 大阪府
  favorite:
    - 新作ドーナツの試食
  cv: 都丸ちよ
