---
shimamura_uzuki:
  name:
    last: 島村
    last_kana: しまむら
    first: 卯月
    first_kana: うずき
  type: cute
  age: 17
  birthday: 4/24
  sign: 牡牛座
  blood: O
  height: 159.0
  weight: 49.0
  bust: 83
  waist: 59
  hip: 87
  handed: right
  from: 東京都
  favorite:
    - 友達と長電話
  cv: 大橋彩香
