---
shinohara_rei:
  name:
    last: 篠原
    last_kana: しのはら
    first: 礼
    first_kana: れい
  type: cool
  age: 27
  birthday: 11/22
  sign: 蠍座
  blood: B
  height: 171.0
  weight: 49.0
  bust: 93
  waist: 58
  hip: 88
  handed: left
  from: 宮崎県
  favorite:
    - 社交ダンス
  cv: ~
