---
shiina_noriko:
  name:
    first: 椎名
    first_kana: しいな
    last: 法子
    last_kana: のりこ
  type: cute
  age: 13
  birthday: 10/10
  sign: 天秤座
  blood: O
  height: 147.0
  weight: 38.0
  bust: 76
  waist: 55
  hip: 79
  handed: right
  from: 大阪府
  favorite:
    - 新作ドーナッツの試食
  cv: 都丸ちよ
