---
shiomi_syuko:
  name:
    last: 塩見
    last_kana: しおみ
    first: 周子
    first_kana: しゅうこ
  type: cool
  age: 18
  birthday:
    month: 12
    day: 12
  sign: 射手座
  blood: B
  height: 163.0
  weight: 45.0
  bust: 82.0
  waist: 56.0
  hip: 81.0
  handed: left
  from: 京都府
  favorite:
    - 献血
    - ダーツ
  cv: ルゥ・ティン
