---
shiragiku_hotaru:
  name:
    last: 白菊
    last_kana: しらぎく
    first: ほたる
    first_kana: ほたる
  type: cute
  age: 13
  birthday: 4/19
  sign: 牡羊座
  blood: AB
  height: 158.0
  weight: 42.0
  bust: 77
  waist: 52
  hip: 79
  handed: left
  from: 鳥取県
  favorite:
    - 笑顔の練習
    - アイドルレッスン
  cv: 天野聡美
