---
shirasaka_koume:
  name:
    last: 白坂
    last_kana: しらさか
    first: 小梅
    first_kana: こうめ
  type: cool
  age: 13
  birthday: 3/28
  sign: 牡羊座
  blood: AB
  height: 142.0
  weight: 34.0
  bust: 65
  waist: 50
  hip: 70
  handed: left
  from: 兵庫県
  favorite:
    - ホラー・スプラッタ映画鑑賞
    - 心霊スポット巡り
  cv: 桜咲千依
