---
shirayuki_chiyo:
  name:
    last: 白雪
    last_kana: しらゆき
    first: 千夜
    first_kana: ちよ
  type: cute
  age: 17
  birthday:
    month: 2
    day: 14
  sign: 水瓶座
  blood: O
  height: 157.0
  weight: 40.0
  bust: 72.0
  waist: 52.0
  hip: 74.0
  handed: right
  from: 北海道
  favorite:
    - 料理
    - 睡眠
  cv: 関口理咲
