---
shirasaka_koume:
  name:
    last: 白坂
    last_kana: しらさか
    first: 小梅
    first_kana: こうめ
  type: cool
  age: 13
  birthday:
    month: 3
    day: 28
  sign: 牡羊座
  blood: AB
  height: 142.0
  weight: 34.0
  bust: 65.0
  waist: 50.0
  hip: 70.0
  handed: left
  from: 兵庫県
  favorite:
    - ホラー・スプラッタ映画鑑賞
    - 心霊スポット巡り
  cv: 桜咲千依
