---
soma_matsumi:
  name:
    last: 相馬
    last_kana: そうま
    first: 夏美
    first_kana: なつみ
  type: passion
  age: 25
  birthday:
    month:  7
    day: 23
  sign: 獅子座
  blood: A
  height: 160.0
  weight: 46.0
  bust: 83.0
  waist: 60.0
  hip: 89.0
  handed: right
  from: 京都府
  favorite:
    - ランニング
  cv: ~
