---
sugisaka_umi:
  name:
    last: 杉坂
    last_kana: すぎさか
    first: 海
    first_kana: うみ
  type: passion
  age: 18
  birthday:
    month: 7
    day: 20
  sign: 蟹座
  blood: B
  height: 162.0
  weight: 45.0
  bust: 88.0
  waist: 58.0
  hip: 86.0
  handed: right
  from: 山口県
  favorite:
    - ウィンドサーフィン
  cv: ~
