---
tachibana_arisu:
  name:
    last: 橘
    last_kana: たちばな
    first: ありす
    first_kana: ありす
  type: cool
  age: 12
  birthday:
    month: 7
    day: 31
  sign: 獅子座
  blood: A
  height: 141.0
  weight: 34.0
  bust: 68.0
  waist: 52.0
  hip: 67.0
  handed: right
  from: 兵庫県
  favorite:
    - ゲーム
    - 読書(ミステリー)
  cv: 佐藤亜美菜
