---
takamori_aiko:
  name:
    last: 高森
    last_kana: たかもり
    first: 藍子
    first_kana: あいこ
  type: passion
  age: 16
  birthday: 7/25
  sign: 獅子座
  blood: O
  height: 155.0
  weight: 42.0
  bust: 74
  waist: 60
  hip: 79
  handed: right
  from: 東京都
  favorite:
    - 近所の公園をお散歩
  cv: 金子有希
