---
takafuji_kako:
  name:
    last: 鷹富士
    last_kana: たかふじ
    first: 茄子
    first_kana: かこ
  type: cool
  age: 20
  birthday:
    month: 1
    day: 1
  sign: 山羊座
  blood: AB
  height: 160.0
  weight: 43.0
  bust: 88.0
  waist: 57.0
  hip: 88.0
  handed: right
  from: 島根県
  favorite:
    - 隠し芸
  cv: 森下来奈
