---
takahashi_reiko:
  name:
    last: 高橋
    last_kana: たかはし
    first: 礼子
    first_kana: れいこ
  type: cool
  age: 31
  birthday:
    month: 5
    day: 8
  sign: 牡羊座
  blood: O
  height: 167.0
  weight: 51.0
  bust: 91.0
  waist: 62.0
  hip: 90.0
  handed: right
  from: 神奈川県
  favorite:
    - パーティーに行くこと
  cv: ~
