---
takagaki_kaede:
  name:
    last: 高垣
    last_kana: たかがき
    first: 楓
    first_kana: かえで
  type: cool
  age: 25
  birthday:
    month: 6
    day: 14
  sign: 双子座
  blood: AB
  height: 171.0
  weight: 49.0
  bust: 81.0
  waist: 57.0
  hip: 83.0
  handed: left
  from: 和歌山県
  favorite:
    - 温泉めぐり
  cv: 早見沙織
