---
togo_ai:
  name:
    last: 東郷
    last_kana: とうごう
    first: あい
    first_kana: あい
  type: cool
  age: 23
  birthday:
    month: 2
    day: 7
  sign: 水瓶座
  blood: AB
  height: 167.0
  weight: 45.0
  bust: 82.0
  waist: 57.0
  hip: 83.0
  handed: both
  from: 福島県
  favorite:
    - サックス
  cv: ~
