---
tsuchiya_ako:
  name:
    first: 土屋
    first_kana: つちや
    last: 亜子
    last_kana: あこ
  type: passion
  age: 15
  birthday: 5/2
  sign: 牡牛座
  blood: B
  height: 156.0
  weight: 42.0
  bust: 85
  waist: 54
  hip: 83
  handed: right
  from: 静岡県
  favorite:
    - 貯金
    - 食べること
  cv: ~
