---
tsuchiya_ako:
  name:
    last: 土屋
    last_kana: つちや
    first: 亜子
    first_kana: あこ
  type: passion
  age: 15
  birthday:
    month: 5
    day: 2
  sign: 牡牛座
  blood: B
  height: 156.0
  weight: 42.0
  bust: 85.0
  waist: 54.0
  hip: 83.0
  handed: right
  from: 静岡県
  favorite:
    - 貯金
    - 食べること
  cv: ~
