---
tsujino_akari:
  name:
    last: 辻野
    last_kana: つじの
    first: あかり
    first_kana: あかり
  type: cute
  age: 15
  birthday:
    month: 11
    day: 5
  sign: 蠍座
  blood: A
  height: 160.0
  weight: 44.0
  bust: 80.0
  waist: 60.0
  hip: 86.0
  handed: right
  from: 山形県
  favorite:
    - ラーメン
    - 編み物
  cv: 梅澤めぐ
