---
tsukimiya_miyabi:
  name:
    last: 月宮
    last_kana: つきみや
    first: 雅
    first_kana: みやび
  type: cute
  age: 18
  birthday: 10/30
  sign: 蠍座
  blood: B
  height: 153.0
  weight: 44.0
  bust: 86
  waist: 56
  hip: 82
  handed: right
  from: 東京都
  favorite:
    - ママとショッピング
  cv: ~
