---
ujiie_mutsumi:
  name:
    last: 氏家
    last_kana: うじいえ
    first: むつみ
    first_kana: むつみ
  type: cool
  age: 13
  birthday:
    month: 7
    day: 13
  sign: 蟹座
  blood: AB
  height: 152.0
  weight: 42.0
  bust: 78.0
  waist: 57.0
  hip: 80.0
  handed: right
  from: 栃木県
  favorite:
    - 冒険小説を読む
    - 冒険映画を見る
  cv: ~
