---
umeki_otoha:
  name:
    first: 梅木
    first_kana: うめき
    last: 音葉
    last_kana: おとは
  type: cool
  age: 19
  birthday: 6/20
  sign: 双子座
  blood: AB
  height: 172.0
  weight: 49.0
  bust: 86
  waist: 58
  hip: 85
  handed: right
  from: 北海道
  favorite:
    - 森林浴
    - ピアノ
  cv: ~
