---
wakabayashi_tomoka:
  name:
    first: 若林
    first_kana: わかばやし
    last: 智香
    last_kana: ともか
  type: passion
  age: 17
  birthday: 8/30
  sign: 乙女座
  blood: A
  height: 156.0
  weight: 45.0
  bust: 82
  waist: 57
  hip: 83
  handed: right
  from: 鹿児島県
  favorite:
    - チアリーディング
  cv: ~
