---
wakabayashi_tomoka:
  name:
    last: 若林
    last_kana: わかばやし
    first: 智香
    first_kana: ともか
  type: passion
  age: 17
  birthday:
    month: 8
    day: 30
  sign: 乙女座
  blood: A
  height: 156.0
  weight: 45.0
  bust: 82.0
  waist: 57.0
  hip: 83.0
  handed: right
  from: 鹿児島県
  favorite:
    - チアリーディング
  cv: ~
