---
yagami_makino:
  name:
    last: 八神
    last_kana: やがみ
    first: マキノ
    first_kana: まきの
  type: cool
  age: 18
  birthday:
    month: 11
    day: 7
  sign: 蠍座
  blood: B
  height: 160.0
  weight: 45.0
  bust: 85.0
  waist: 56.0
  hip: 83.0
  handed: right
  from: 岐阜県
  favorite:
    - 諜報活動
  cv: 二ノ宮ゆい
