---
yaguchi_miu:
  name:
    first: 矢口
    first_kana: やぐち
    last: 美羽
    last_kana: みう
  type: passion
  age: 14
  birthday: 7/10
  sign: 蟹座
  blood: B
  height: 150.0
  weight: 41.0
  bust: 81
  waist: 56
  hip: 80
  handed: right
  from: 千葉県
  favorite:
    - メール
  cv: ~
