---
yamato_aki:
  name:
    last: 大和
    last_kana: やまと
    first: 亜季
    first_kana: あき
  type: cool
  age: 21
  birthday:
    month: 12
    day: 16
  sign: 射手座
  blood: O
  height: 165.0
  weight: 51.0
  bust: 92.0
  waist: 60.0
  hip: 85.0
  handed: left
  from: 福岡県
  favorite:
    - サバゲー
    - プラモ収集
  cv: 村中知
