---
yanagi_kiyora:
  name:
    last: 柳清
    last_kana: やなぎ
    first: 良
    first_kana: きよら
  type: cute
  age: 23
  birthday:
    month: 5
    day: 12
  sign: 牡羊座
  blood: O
  height: 158.0
  weight: 47.0
  bust: 85.0
  waist: 58.0
  hip: 86.0
  handed: right
  from: 愛媛県
  favorite:
    - ドキュメンタリー番組鑑賞
  cv: ~
