---
yamase_miyuki:
  name:
    last: 柳瀬
    last_kana: やなせ
    first: 美由紀
    first_kana: みゆき
  type: cute
  age: 14
  birthday:
    month: 3
    day: 16
  sign: 魚座
  blood: O
  height: 144.0
  weight: 33.0
  bust: 75.0
  waist: 54.0
  hip: 77.0
  handed: right
  from: 北海道
  favorite:
    - ぬいぐるみ集め
  cv: ~
