---
yao_fueifuei:
  name:
    last: 楊
    last_kana: やお
    first: 菲菲
    first_kana: ふぇいふぇい
  type: cute
  age: 15
  birthday:
    month: 9
    day: 29
  sign: 天秤座
  blood: O
  height: 152.0
  weight: 41.0
  bust: 82.0
  waist: 58.0
  hip: 84.0
  handed: right
  from: 香港
  favorite:
    - 料理
  cv: ~
