---
yokoyama_chika:
  name:
    last: 横山
    last_kana: よこやま
    first: 千佳
    first_kana: ちか
  type: cute
  age: 9
  birthday:
    month: 12
    day: 18
  sign: 射手座
  blood: A
  height: 127.0
  weight: 31.0
  bust: 61.0
  waist: 55.0
  hip: 65.0
  handed: right
  from: 宮崎県
  favorite:
    - 魔法少女ごっこ
  cv: ~
