---
yorita_yoshino:
  name:
    last: 依田
    last_kana: よりた
    first: 芳乃
    first_kana: よしの
  type: passion
  age: 16
  birthday:
    month: 7
    day: 3
  sign: 蟹座
  blood: O
  height: 151.0
  weight: 40.0
  bust: 73.0
  waist: 53.0
  hip: 73.0
  handed: right
  from: 鹿児島県
  favorite:
    - 悩み事解決
    - 石ころ集め
    - 失せ物探し
  cv: 高田憂希
