---
yumemi_riamu:
  name:
    first: 夢見
    first_kana: ゆめみ
    last: りあむ
    last_kana: りあむ
  type: passion
  age: 19
  birthday: 9/12
  sign: 乙女座
  blood: AB
  height: 149.0
  weight: リンゴたくさん
  bust: でっかい(95)
  waist: ふつう
  hip: たぶんふつう
  handed: right
  from: やさしい世界
  favorite:
    - 夜中の意味深ポエム
    - 現場参戦
  cv: 星希成奏
