---
zaizen_tokiko:
  name:
    last: 財前
    last_kana: ざいぜん
    first: 時子
    first_kana: ときこ
  type: passion
  age: 21
  birthday:
    month: 4
    day: 18
  sign: 牡羊座
  blood: B
  height: 168.0
  weight: 46.0
  bust: 83.0
  waist: 55.0
  hip: 85.0
  handed: right
  from: 愛知県(名古屋市)
  favorite:
    - お仕置き
    - 豚を料理すること
  cv: ~
