---
senkawa_chihiro:
  name:
    last: 千川
    last_lana: せんかわ
    first: ちひろ
    first_kana: ちひろ
  type: ~
  age: ??
  birthday:
    month: 11
    day: 28
  sign: 射手座
  blood: A
  height: 154.0
  weight: ひ・み・つ
  bust: 82.0
  waist: 58.0
  hip: 84.0
  handed: right
  from: 東京都
  favorite:
    - コスプレ
    - パーティ
  cv: 佐藤利奈
