---
veteran_trainer:
  name:
    last: 青木
    last_kana: あおき
    first: 聖
    first_kana: せい
  type: passion
  age: 26
  birthday:
    month: 9
    day: 10
  sign: 乙女座
  blood: A
  height: 163.0
  weight: 45.0
  bust: 83.0
  waist: 56.0
  hip: 84.0
  handed: right
  from: 栃木県
  favorite:
    - デイトレード
  cv: 藤村歩
