# frozen_string_literal: true

require 'active_support/all'
require 'yaml'
require 'rubiderella/assistant'
require 'rubiderella/assistant/name'
require 'rubiderella/assistant/birthday'
require 'rubiderella/errors'
require 'rubiderella/idol'
require 'rubiderella/idol/name'
require 'rubiderella/idol/birthday'
require 'rubiderella/trainer'
require 'rubiderella/trainer/name'
require 'rubiderella/trainer/birthday'
require 'rubiderella/version'
require 'cinderella_girls'
require 'cinderella_girls/idol'
